"use strict";
const http=require("node:http");
class HologramServer{
  constructor({port=17821}={}){this.port=port;this.server=null;this.clients=new Set();this.last=null;}
  status(){return{active:Boolean(this.server?.listening),port:this.port,url:`http://127.0.0.1:${this.port}/hologram`,clients:this.clients.size};}
  async start(){if(this.server)return this.status();this.server=http.createServer((req,res)=>this.handle(req,res));await new Promise((resolve,reject)=>{this.server.once("error",reject);this.server.listen(this.port,"127.0.0.1",()=>{this.server.off("error",reject);resolve()})});return this.status()}
  async stop(){if(!this.server)return;for(const c of this.clients)try{c.end()}catch{}this.clients.clear();await new Promise(r=>this.server.close(()=>r()));this.server=null;}
  push(message={}){this.last={platform:String(message.platform||""),username:String(message.displayName||message.username||"User"),message:String(message.message||""),role:String(message.role||""),avatar:String(message.avatar||""),color:String(message.color||""),timestamp:Date.now()};const line=`data: ${JSON.stringify(this.last)}\n\n`;for(const c of [...this.clients])try{c.write(line)}catch{this.clients.delete(c)}return this.last;}
  handle(req,res){const u=new URL(req.url,"http://127.0.0.1");if(u.pathname==="/events"){res.writeHead(200,{"content-type":"text/event-stream","cache-control":"no-cache","connection":"keep-alive","access-control-allow-origin":"*"});if(this.last)res.write(`data: ${JSON.stringify(this.last)}\n\n`);this.clients.add(res);req.on("close",()=>this.clients.delete(res));return}if(u.pathname!=="/hologram"&&u.pathname!=="/"){res.writeHead(404);return res.end("Not found")}res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});res.end(`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;width:100%;height:100%;overflow:hidden;background:transparent;font-family:Inter,Segoe UI,Arial,sans-serif;color:white}#wrap{position:absolute;left:3%;bottom:4%;max-width:70%;padding:13px 18px;border:1px solid #4fd8ff66;border-left:4px solid var(--c,#4fd8ff);border-radius:14px;background:linear-gradient(135deg,#07101bee,#102238dd);box-shadow:0 0 28px #4fd8ff44;opacity:0;transform:translateY(15px);transition:.2s}#wrap.on{opacity:1;transform:none}.name{font-size:15px;font-weight:900;color:var(--c,#4fd8ff)}.role{font-size:10px;margin-left:8px;padding:2px 5px;border-radius:5px;background:#ffffff22}.msg{font-size:22px;font-weight:700;margin-top:5px;text-shadow:0 0 14px #000}</style></head><body><div id="wrap"><span class="name" id="name"></span><span class="role" id="role"></span><div class="msg" id="msg"></div></div><script>const w=document.getElementById('wrap'),n=document.getElementById('name'),r=document.getElementById('role'),m=document.getElementById('msg');let t;new EventSource('/events').onmessage=e=>{try{const d=JSON.parse(e.data),colors={twitch:'#9146ff',cng:'#2f9cff',tiktok:'#f1f1f1',youtube:'#ff3030'};w.style.setProperty('--c',d.color||colors[d.platform]||'#4fd8ff');n.textContent=d.username||'User';r.textContent=d.role||d.platform||'';m.textContent=d.message||'';w.classList.add('on');clearTimeout(t);t=setTimeout(()=>w.classList.remove('on'),9000)}catch{}}</script></body></html>`)}
}
module.exports={HologramServer};
