"use strict";
const crypto=require("node:crypto");
const http=require("node:http");
class TwitchOAuth{
  constructor({secretStore,settingsStore,shell,port=48732}={}){this.secretStore=secretStore;this.settingsStore=settingsStore;this.shell=shell;this.port=port;}
  async begin({clientId,clientSecret,scopes=["chat:read","chat:edit"]}={}){const cfg=await this.settingsStore.get("twitchOAuth")||{};clientId=String(clientId||cfg.clientId||"").trim();clientSecret=String(clientSecret||"").trim();if(!clientId)throw new Error("Twitch Client ID fehlt.");if(clientSecret)await this.secretStore.set("twitch.clientSecret",clientSecret);const state=crypto.randomBytes(24).toString("hex"),redirectUri=`http://127.0.0.1:${this.port}/oauth/twitch/callback`;await this.settingsStore.set("twitchOAuth",{clientId,redirectUri,scopes});const url=new URL("https://id.twitch.tv/oauth2/authorize");url.searchParams.set("client_id",clientId);url.searchParams.set("redirect_uri",redirectUri);url.searchParams.set("response_type","code");url.searchParams.set("scope",scopes.join(" "));url.searchParams.set("state",state);const pending=this.waitCallback(state,redirectUri);await this.shell.openExternal(url.toString());return pending;}
  waitCallback(state,redirectUri){return new Promise((resolve,reject)=>{const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://127.0.0.1");if(u.pathname!=="/oauth/twitch/callback"){res.writeHead(404);return res.end();}if(u.searchParams.get("state")!==state)throw new Error("Ungültiger Twitch OAuth-State.");if(u.searchParams.get("error"))throw new Error(u.searchParams.get("error_description")||u.searchParams.get("error"));const code=u.searchParams.get("code");const result=await this.exchange(code,redirectUri);res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end("<h2>BATTO MULTI-CHAT</h2><p>Twitch wurde erfolgreich verbunden.</p>");server.close();resolve(result);}catch(e){res.writeHead(400);res.end(String(e.message||e));server.close();reject(e);}});server.listen(this.port,"127.0.0.1");server.on("error",reject);});}
  async exchange(code,redirectUri){const cfg=await this.settingsStore.get("twitchOAuth")||{};const secret=await this.secretStore.get("twitch.clientSecret");if(!secret)throw new Error("Twitch Client Secret fehlt.");const body=new URLSearchParams({client_id:cfg.clientId,client_secret:secret,code,grant_type:"authorization_code",redirect_uri:redirectUri});const response=await fetch("https://id.twitch.tv/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.message||`Twitch OAuth HTTP ${response.status}`);await this.save(data);return this.status();}
  async refresh(){const cfg=await this.settingsStore.get("twitchOAuth")||{};const secret=await this.secretStore.get("twitch.clientSecret"),refresh=await this.secretStore.get("twitch.refreshToken");if(!refresh)throw new Error("Kein Twitch Refresh Token vorhanden.");const body=new URLSearchParams({grant_type:"refresh_token",refresh_token:refresh,client_id:cfg.clientId,client_secret:secret});const response=await fetch("https://id.twitch.tv/oauth2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json();if(!response.ok)throw new Error(data.message||`Twitch OAuth HTTP ${response.status}`);await this.save(data);return this.status();}
  async save(data){if(data.access_token)await this.secretStore.set("twitch.accessToken",data.access_token);if(data.refresh_token)await this.secretStore.set("twitch.refreshToken",data.refresh_token);await this.settingsStore.set("twitchSession",{scopes:data.scope||[],expiresAt:Date.now()+Number(data.expires_in||0)*1000,updatedAt:Date.now()});}
  async accessToken(){const s=await this.settingsStore.get("twitchSession")||{};if(s.expiresAt&&Date.now()>s.expiresAt-120000)await this.refresh();return this.secretStore.get("twitch.accessToken");}
  async status(){const token=await this.secretStore.get("twitch.accessToken"),s=await this.settingsStore.get("twitchSession")||{};return{connected:Boolean(token),scopes:s.scopes||[],expiresAt:s.expiresAt||0};}
  async revoke(){for(const k of ["twitch.accessToken","twitch.refreshToken"])await this.secretStore.delete(k);await this.settingsStore.set("twitchSession",{});return this.status();}
}
module.exports={TwitchOAuth};
