"use strict";
const types=[['text','Text','Freier Hinweis'],['goal','Ziel','Follower oder Likes'],['timer','Timer','Stream-Laufzeit'],['chat','Chat','Live-Nachrichten'],['giftFeed','Geschenk-Feed','Geschenke in Echtzeit'],['giftAlarm','Geschenk-Alarm','Letztes Geschenk groß'],['topList','Topliste','Top-Gifter'],['likeCounter','Like-Zähler','Aktuelle Likes'],['coHost','Co-Host','Gastname und Status'],['treasure','Schatztruhe','Truhen-Ereignisse'],['portal','Portal','Portal-Ereignisse'],['tiktokEvents','TikTok-Ereignisse','Lokaler Ereignisfeed'],['wheel','Glücksrad','Lokales Wheel'],['poll','Umfrage','Live-Abstimmung'],['wordCloud','Wortwolke','Chatbegriffe'],['logo','Logo','App-/Brand-Logo'],['image','Bild','Freies Bild']];
let config=null,selected=null,drag=null;const $=s=>document.querySelector(s);const stage=$('#stage');
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
async function load(){const [cfg,status]=await Promise.all([fetch('/api/config').then(r=>r.json()),fetch('/api/status').then(r=>r.json())]);config=cfg;$('#overlay-url').value=status.overlayUrl;const value=`${config.width}x${config.height}`;if([...$('#preset').options].some(o=>o.value===value))$('#preset').value=value;renderTypes();renderStage();}
function renderTypes(){$('#element-types').innerHTML=types.map(([id,name,desc])=>`<button data-add="${id}"><strong>${name}</strong><small>${desc}</small></button>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addElement(b.dataset.add));}
function defaultElement(type){const found=types.find(x=>x[0]===type);return{id:`${type}-${Date.now()}`,type,title:found?.[1]||type,text:'',x:8,y:12,width:22,height:12,zIndex:config.elements.length+1,visible:true,locked:false,fontSize:type==='chat'||type==='giftFeed'?26:34,fontFamily:'Inter, Segoe UI, Arial, sans-serif',fontWeight:800,textColor:'#ffffff',accentColor:'#4fd8ff',backgroundColor:'#0b1522',backgroundOpacity:.72,borderColor:'#33546b',borderWidth:1,borderRadius:14,padding:12,alignment:'center',shadow:18,value:0,target:1000,maximumItems:8,settings:{}}}
function addElement(type){const el=defaultElement(type);config.elements.push(el);selected=el;renderStage();renderInspector();}
function displayValue(el){if(el.type==='goal')return `${el.value||0} / ${el.target||1000}`;if(el.type==='timer')return '02:47:13';if(el.type==='chat')return 'Live-Chat';if(el.type==='giftFeed')return 'Geschenke';if(el.type==='coHost')return 'Kein Co-Host';return el.text||el.title}
function renderStage(){stage.style.aspectRatio=`${config.width}/${config.height}`;stage.innerHTML=config.elements.filter(e=>e.visible!==false).sort((a,b)=>(a.zIndex||0)-(b.zIndex||0)).map(el=>`<div class="stage-element ${selected?.id===el.id?'selected':''}" data-id="${el.id}" style="left:${el.x}%;top:${el.y}%;width:${el.width}%;height:${el.height}%;z-index:${el.zIndex};--accent:${el.accentColor};--border:${el.borderColor};border-width:${el.borderWidth}px;border-radius:${el.borderRadius}px;font-size:${el.fontSize}px"><span class="title">${esc(el.title)}</span><span class="value">${esc(displayValue(el))}</span></div>`).join('');stage.querySelectorAll('.stage-element').forEach(node=>{node.onmousedown=e=>startDrag(e,node.dataset.id);node.onclick=e=>{e.stopPropagation();selected=config.elements.find(x=>x.id===node.dataset.id);renderStage();renderInspector();}});}
function startDrag(e,id){const el=config.elements.find(x=>x.id===id);if(!el||el.locked)return;selected=el;const rect=stage.getBoundingClientRect();drag={el,startX:e.clientX,startY:e.clientY,x:el.x,y:el.y,rect};document.onmousemove=moveDrag;document.onmouseup=endDrag;e.preventDefault();}
function moveDrag(e){if(!drag)return;drag.el.x=Math.max(0,Math.min(100-drag.el.width,drag.x+(e.clientX-drag.startX)/drag.rect.width*100));drag.el.y=Math.max(0,Math.min(100-drag.el.height,drag.y+(e.clientY-drag.startY)/drag.rect.height*100));renderStage();renderInspector(false)}
function endDrag(){drag=null;document.onmousemove=null;document.onmouseup=null;}
function renderInspector(fill=true){const form=$('#inspector'),empty=$('#inspector-empty');if(!selected){form.hidden=true;empty.hidden=false;return}form.hidden=false;empty.hidden=true;if(!fill)return;$('#el-title').value=selected.title||'';$('#el-text').value=selected.text||'';$('#el-value').value=selected.value||0;$('#el-target').value=selected.target||0;$('#el-x').value=selected.x;$('#el-y').value=selected.y;$('#el-width').value=selected.width;$('#el-height').value=selected.height;$('#el-font').value=selected.fontSize;$('#el-z').value=selected.zIndex;$('#el-visible').checked=selected.visible!==false;}
function pullInspector(){if(!selected)return;selected.title=$('#el-title').value;selected.text=$('#el-text').value;selected.value=Number($('#el-value').value)||0;selected.target=Number($('#el-target').value)||0;selected.x=Number($('#el-x').value)||0;selected.y=Number($('#el-y').value)||0;selected.width=Math.max(2,Number($('#el-width').value)||2);selected.height=Math.max(2,Number($('#el-height').value)||2);selected.fontSize=Math.max(8,Number($('#el-font').value)||8);selected.zIndex=Number($('#el-z').value)||1;selected.visible=$('#el-visible').checked;renderStage();}
$('#inspector').addEventListener('input',pullInspector);$('#delete').onclick=()=>{if(!selected)return;config.elements=config.elements.filter(x=>x.id!==selected.id);selected=null;renderStage();renderInspector()};$('#save').onclick=async()=>{const r=await fetch('/api/config',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(config)});config=await r.json();$('#local-status').textContent='Gespeichert';setTimeout(()=>$('#local-status').textContent='Lokal aktiv',1200)};$('#copy-url').onclick=()=>navigator.clipboard.writeText($('#overlay-url').value);$('#test-chat').onclick=()=>fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({platform:'tiktok',username:'Crazy_Batto',message:'BATTO MULTI-CHAT Overlay-Test'})});$('#test-gift').onclick=()=>fetch('/api/event',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({platform:'tiktok',eventType:'gift',title:'Geschenk-Test'})});$('#clear').onclick=()=>fetch('/api/clear',{method:'POST'});$('#close-btn').onclick=()=>window.close();$('#preset').onchange=()=>{const[w,h]=$('#preset').value.split('x').map(Number);config.width=w;config.height=h;renderStage()};stage.onclick=()=>{selected=null;renderStage();renderInspector()};load().catch(e=>{$('#local-status').textContent=`Fehler: ${e.message}`});
