"use strict";
const root=document.getElementById("overlay");let config={elements:[]},state={messages:[],events:[]},timerStarted=Date.now();const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function style(el){return`left:${el.x}%;top:${el.y}%;width:${el.width}%;height:${el.height}%;z-index:${el.zIndex};font-size:${el.fontSize}px;font-family:${el.fontFamily};font-weight:${el.fontWeight};color:${el.textColor};background:${hexAlpha(el.backgroundColor,el.backgroundOpacity)};border:${el.borderWidth}px solid ${el.borderColor};border-radius:${el.borderRadius}px;padding:${el.padding}px;box-shadow:0 0 ${el.shadow}px ${hexAlpha(el.accentColor,.25)};--accent:${el.accentColor};`}
function hexAlpha(hex,a){const h=String(hex||"#000000").replace('#','');if(h.length!==6)return`rgba(0,0,0,${a})`;return`rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${Number(a)})`}
function title(el){return`<span class="overlay-title">${esc(el.title||'')}</span>`}
function chatHtml(el){const items=state.messages.slice(-Number(el.maximumItems||8));return items.map(m=>`<div class="msg ${esc(m.platform||'')}"><div class="meta"><span class="platform">${esc(m.platform||'chat')}</span><span class="user">${esc(m.displayName||m.username||'User')}</span></div><div class="text">${esc(m.message||m.text||'')}</div></div>`).join('')}
function giftsHtml(el){const items=state.events.filter(e=>(e.eventType||e.type)==='gift'||String(e.title||'').toLowerCase().includes('geschenk')).slice(-Number(el.maximumItems||8));return items.map(e=>`<div class="event-card">${esc(e.username||e.name||'')} ${esc(e.message||e.title||'Geschenk')}</div>`).join('')}
function elementHtml(el){if(el.visible===false)return'';let body='';if(el.type==='goal'){const pct=Math.max(0,Math.min(100,(Number(el.value)||0)/Math.max(1,Number(el.target)||1)*100));body=`${title(el)}<span class="overlay-value">${esc(el.value||0)} / ${esc(el.target||0)}</span><span class="progress"><i style="width:${pct}%"></i></span>`}else if(el.type==='timer'){body=`${title(el)}<span class="overlay-value" data-timer>00:00:00</span>`}else if(el.type==='chat'){body=`${title(el)}<div class="overlay-chat">${chatHtml(el)}</div>`}else if(el.type==='giftFeed'){body=`${title(el)}<div class="overlay-gifts">${giftsHtml(el)}</div>`}else if(el.type==='giftAlarm'){const e=state.events.filter(x=>(x.eventType||x.type)==='gift').at(-1);body=`${title(el)}<span class="overlay-value">${esc(e?.message||e?.title||'Kein Geschenk')}</span>`}else if(el.type==='likeCounter'){const likes=state.events.filter(x=>(x.eventType||x.type)==='like').reduce((n,x)=>n+Number(x.likeCount||x.value||x.data?.likeCount||0),0);body=`${title(el)}<span class="overlay-value">${likes}</span>`}else if(el.type==='coHost'){body=`${title(el)}<span class="overlay-value">${esc(el.text||'Kein Co-Host')}</span>`}else if(el.type==='topList'){body=`${title(el)}<span class="overlay-value">Top-Gifter</span>`}else if(el.type==='tiktokEvents'){const e=state.events.at(-1);body=`${title(el)}<span class="overlay-value">${esc(e?.title||e?.message||'Keine Ereignisse')}</span>`}else if(el.type==='logo'){body=`${title(el)}<span class="overlay-value">BATTO</span>`}else{body=`${title(el)}<span class="overlay-value">${esc(el.text||el.title||'')}</span>`}return`<section class="overlay-element overlay-${el.type}" data-id="${esc(el.id)}" style="${style(el)}">${body}</section>`}
function render(){root.style.background=config.transparent===false?hexAlpha(config.backgroundColor,config.backgroundOpacity):'transparent';root.innerHTML=(config.elements||[]).sort((a,b)=>(a.zIndex||0)-(b.zIndex||0)).map(elementHtml).join('');updateTimers()}
function updateTimers(){const elapsed=Math.max(0,Date.now()-timerStarted),total=Math.floor(elapsed/1000),h=String(Math.floor(total/3600)).padStart(2,'0'),m=String(Math.floor(total%3600/60)).padStart(2,'0'),s=String(total%60).padStart(2,'0');document.querySelectorAll('[data-timer]').forEach(x=>x.textContent=`${h}:${m}:${s}`)}
setInterval(updateTimers,1000);
async function boot(){const data=await fetch('/api/state').then(r=>r.json());config=data.config||data.state?.config||config;state=data.state||state;timerStarted=state.startedAt||Date.now();render()}
const es=new EventSource('/events');es.onmessage=ev=>{try{const data=JSON.parse(ev.data);if(data.type==='config'){config=data.config||config;render();return}if(data.type==='clear'){state={...state,messages:[],events:[]};render();return}if(data.type==='chat'){state.messages.push(data);if(state.messages.length>250)state.messages.shift();render();return}state.events.push(data);if(state.events.length>100)state.events.shift();render()}catch{}};
boot().catch(()=>{});
