"use strict";
const path=require("node:path");
const {app,ipcMain,safeStorage,shell,clipboard}=require("electron");
const {ChatWindowManager}=require("./services/chat-window-manager.cjs");
const {ChatCore}=require("./services/chat-core.cjs");
const {PlatformManager}=require("./services/platform-manager.cjs");
const {TikTokAdapter}=require("./platforms/tiktok/tiktok-adapter.cjs");
const {TwitchAdapter}=require("./platforms/twitch/twitch-adapter.cjs");
const {YouTubeAdapter}=require("./platforms/youtube/youtube-adapter.cjs");
const {CngAdapter}=require("./platforms/cng/cng-adapter.cjs");
const {ObsWebSocketService}=require("./services/obs-websocket.cjs");
const {StreamOverlayServer}=require("./services/stream-overlay-server.cjs");
const {HologramServer}=require("./services/hologram-server.cjs");
const {SecretStore}=require("./storage/secret-store.cjs");
const {SettingsStore}=require("./storage/settings-store.cjs");
const {EulerOAuth}=require("./platforms/tiktok/euler-oauth.cjs");
const {EulerClient}=require("./platforms/tiktok/euler-client.cjs");
const {TwitchOAuth}=require("./platforms/twitch/twitch-oauth.cjs");
const {YouTubeOAuth}=require("./platforms/youtube/youtube-oauth.cjs");

const core=new ChatCore(),platforms=new PlatformManager(core),obs=new ObsWebSocketService();
platforms.register("tiktok",new TikTokAdapter());platforms.register("cng",new CngAdapter());
let manager,settings,secrets,eulerOAuth,euler,twitchOAuth,youtubeOAuth,streamOverlay,hologram;
let tiktokContext={username:"",roomId:"",anchorId:""};
const DEFAULT_SETTINGS={accounts:{tiktok:{username:""},twitch:{},youtube:{},cng:{websocketUrl:""}},obs:{url:"ws://127.0.0.1:4455"},tiktokOAuth:{clientId:"",redirectUri:"http://127.0.0.1:48731/oauth/tiktok/callback",scopes:["webcast:fetch","webcast:chat","webcast:mute","webcast:ban","webcast:comments","webcast:moderators","webcast:sensitive_words","user:info"]},tiktokSession:{},twitchOAuth:{clientId:"",redirectUri:"http://127.0.0.1:48732/oauth/twitch/callback",scopes:["chat:read","chat:edit"]},twitchSession:{},youtubeOAuth:{clientId:"",redirectUri:"http://127.0.0.1:48733",scopes:["https://www.googleapis.com/auth/youtube.readonly"]},youtubeSession:{},tts:{enabled:false,language:"de-DE",rate:1,pitch:1,volume:1,platforms:["twitch","cng","tiktok","youtube"]}};
async function resolveTikTokContext(username){username=String(username||tiktokContext.username||"").trim().replace(/^@/,"");if(!username)throw new Error("TikTok @Username fehlt.");tiktokContext.username=username;const[room,user]=await Promise.all([euler.roomId(username),euler.userId(username)]);tiktokContext.roomId=String(room?.response?.room_id||room?.room_id||room?.response?.roomId||"");tiktokContext.anchorId=String(user?.response?.user_id||user?.user_id||user?.response?.userId||"");return{...tiktokContext}}
async function connectTwitch(channel){const token=await twitchOAuth.accessToken();if(!token)throw new Error("Twitch ist nicht angemeldet.");const s=await twitchOAuth.status();channel=String(channel||s.profile?.channel||s.profile?.username||"").trim().replace(/^#/,"");if(!channel)throw new Error("Twitch-Kanal fehlt.");return platforms.connect("twitch",{channel,token,username:s.profile?.username||channel})}
function registerIpc(){
  ipcMain.handle("chat:history",(_e,o={})=>core.history(o.limit));ipcMain.handle("chat:clear",(_e,p="all")=>core.clear(p));ipcMain.handle("chat:statuses",()=>platforms.statuses());ipcMain.handle("chat:connect",async(_e,p,c)=>{const r=await platforms.connect(p,c||{});if(p==="tiktok"&&c?.username){const accounts=await settings.get("accounts");accounts.tiktok={...(accounts.tiktok||{}),username:String(c.username)};await settings.set("accounts",accounts);tiktokContext.username=String(c.username).replace(/^@/,"")}return r});ipcMain.handle("chat:disconnect",(_e,p)=>platforms.disconnect(p));
  ipcMain.handle("window:alwaysOnTop",()=>manager.toggleAlwaysOnTop());ipcMain.handle("settings:get",()=>settings.get());ipcMain.handle("settings:patch",(_e,v)=>settings.patch(v||{}));
  ipcMain.handle("obs:status",()=>obs.status());ipcMain.handle("obs:connect",async(_e,c)=>{const password=String(c?.password||await secrets.get("obs.password")||"");const r=await obs.connect({...c,password});await settings.set("obs",{url:c?.url||"ws://127.0.0.1:4455"});if(c?.password)await secrets.set("obs.password",c.password);return r});ipcMain.handle("obs:disconnect",()=>obs.disconnect());ipcMain.handle("obs:savedPassword",async()=>Boolean(await secrets.get("obs.password")));ipcMain.handle("obs:scenes",()=>obs.scenes());ipcMain.handle("obs:sceneItems",(_e,s)=>obs.sceneItems(s));ipcMain.handle("obs:setScene",(_e,s)=>obs.setScene(s));ipcMain.handle("obs:setItemEnabled",(_e,v)=>obs.setSceneItemEnabled(v.sceneName,v.sceneItemId,v.enabled));ipcMain.handle("obs:ensureOverlay",(_e,v={})=>obs.ensureOverlaySource({...v,url:streamOverlay.status().overlayUrl}));ipcMain.handle("obs:ensureHologram",(_e,v={})=>obs.ensureOverlaySource({...v,inputName:v.inputName||"BATTO Hologramm",url:hologram.status().url,width:v.width||1200,height:v.height||500}));
  ipcMain.handle("overlay:status",()=>streamOverlay.status());ipcMain.handle("overlay:open",()=>shell.openExternal(streamOverlay.status().overlayUrl));ipcMain.handle("overlay:openEditor",()=>shell.openExternal(streamOverlay.status().editorUrl));ipcMain.handle("overlay:copyUrl",()=>{const u=streamOverlay.status().overlayUrl;clipboard.writeText(u);return u});ipcMain.handle("overlay:testChat",()=>{const m={platform:"tiktok",username:"Crazy_Batto",displayName:"Crazy_Batto",message:"BATTO MULTI-CHAT Overlay-Test",role:"moderator"};streamOverlay.pushChat(m);hologram.push(m);return true});ipcMain.handle("overlay:testEvent",()=>{streamOverlay.pushEvent({platform:"tiktok",eventType:"gift",title:"Geschenk-Test · BATTO MULTI-CHAT"});return true});ipcMain.handle("hologram:status",()=>hologram.status());ipcMain.handle("hologram:open",()=>shell.openExternal(hologram.status().url));ipcMain.handle("hologram:copyUrl",()=>{const u=hologram.status().url;clipboard.writeText(u);return u});
  ipcMain.handle("tiktok:oauthStatus",()=>eulerOAuth.status());ipcMain.handle("tiktok:oauthBegin",(_e,c={})=>eulerOAuth.begin(c));ipcMain.handle("tiktok:oauthRefresh",()=>eulerOAuth.refresh());ipcMain.handle("tiktok:oauthRevoke",()=>eulerOAuth.revoke());ipcMain.handle("tiktok:resolveContext",(_e,u)=>resolveTikTokContext(u));ipcMain.handle("tiktok:context",()=>({...tiktokContext}));ipcMain.handle("tiktok:gifts",()=>euler.gifts());ipcMain.handle("tiktok:giftSearch",(_e,q)=>euler.searchGifts(q));ipcMain.handle("tiktok:sendChat",async(_e,m)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.sendChat(tiktokContext.roomId,m)});ipcMain.handle("tiktok:muted",async()=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.muted(tiktokContext.roomId)});ipcMain.handle("tiktok:mute",async(_e,{userId,duration,commentMsgId}={})=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.mute(tiktokContext.roomId,userId,duration||300,commentMsgId)});ipcMain.handle("tiktok:unmute",async(_e,u)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.unmute(tiktokContext.roomId,u)});ipcMain.handle("tiktok:banned",async()=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.banned(tiktokContext.roomId)});ipcMain.handle("tiktok:ban",async(_e,{userId,commentMsgId}={})=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.ban(tiktokContext.roomId,userId,commentMsgId)});ipcMain.handle("tiktok:unban",async(_e,u)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.unban(tiktokContext.roomId,u)});ipcMain.handle("tiktok:moderators",async()=>{if(!tiktokContext.anchorId)await resolveTikTokContext();return euler.moderators(tiktokContext.anchorId)});ipcMain.handle("tiktok:addModerator",async(_e,u)=>{if(!tiktokContext.anchorId)await resolveTikTokContext();return euler.addModerator(tiktokContext.anchorId,u)});ipcMain.handle("tiktok:removeModerator",async(_e,u)=>{if(!tiktokContext.anchorId)await resolveTikTokContext();return euler.removeModerator(tiktokContext.anchorId,u)});ipcMain.handle("tiktok:comments",async(_e,en)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.toggleComments(tiktokContext.roomId,en)});ipcMain.handle("tiktok:sensitiveWords",async()=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.sensitiveWords(tiktokContext.roomId)});ipcMain.handle("tiktok:addSensitiveWord",async(_e,w)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.addSensitiveWord(tiktokContext.roomId,w)});ipcMain.handle("tiktok:deleteSensitiveWord",async(_e,w)=>{if(!tiktokContext.roomId)await resolveTikTokContext();return euler.deleteSensitiveWord(tiktokContext.roomId,w)});
  ipcMain.handle("twitch:oauthStatus",()=>twitchOAuth.status());ipcMain.handle("twitch:oauthBegin",(_e,c={})=>twitchOAuth.begin(c));ipcMain.handle("twitch:oauthRefresh",()=>twitchOAuth.refresh());ipcMain.handle("twitch:oauthRevoke",()=>twitchOAuth.revoke());ipcMain.handle("twitch:connect",(_e,c)=>connectTwitch(c));
  ipcMain.handle("youtube:oauthStatus",()=>youtubeOAuth.status());ipcMain.handle("youtube:oauthBegin",(_e,c={})=>youtubeOAuth.begin(c));ipcMain.handle("youtube:oauthRefresh",()=>youtubeOAuth.refresh());ipcMain.handle("youtube:oauthRevoke",()=>youtubeOAuth.revoke());ipcMain.handle("youtube:connect",(_e,c={})=>platforms.connect("youtube",c));
  ipcMain.handle("cng:connect",async(_e,c={})=>{const accounts=await settings.get("accounts");accounts.cng={...(accounts.cng||{}),websocketUrl:String(c.websocketUrl||"")};await settings.set("accounts",accounts);if(c.token)await secrets.set("cng.token",c.token);return platforms.connect("cng",{websocketUrl:c.websocketUrl,token:c.token||await secrets.get("cng.token")})});
}
app.whenReady().then(async()=>{const userData=app.getPath("userData");settings=new SettingsStore(path.join(userData,"settings.json"),DEFAULT_SETTINGS);await settings.load();secrets=new SecretStore(path.join(userData,"secrets.dat"),safeStorage);eulerOAuth=new EulerOAuth({secretStore:secrets,settingsStore:settings,shell});euler=new EulerClient({oauth:eulerOAuth});twitchOAuth=new TwitchOAuth({secretStore:secrets,settingsStore:settings,shell});youtubeOAuth=new YouTubeOAuth({secretStore:secrets,settingsStore:settings,shell});platforms.register("twitch",new TwitchAdapter());platforms.register("youtube",new YouTubeAdapter({oauth:youtubeOAuth}));const accounts=await settings.get("accounts");tiktokContext.username=String(accounts?.tiktok?.username||"").replace(/^@/,"");streamOverlay=new StreamOverlayServer({webRoot:path.join(__dirname,"stream-overlay"),configFile:path.join(userData,"stream-overlay.json"),port:48621});hologram=new HologramServer({port:17821});try{await streamOverlay.start()}catch(e){console.error("Stream-Overlay konnte nicht gestartet werden:",e)}try{await hologram.start()}catch(e){console.error("Hologramm konnte nicht gestartet werden:",e)}manager=new ChatWindowManager({userDataFile:path.join(userData,"multichat-window.json"),preloadPath:path.join(__dirname,"preload.cjs"),rendererPath:path.join(__dirname,"renderer","multi-chat.html"),onClosed:()=>{if(process.platform!=="darwin")app.quit()}});await manager.load();registerIpc();manager.create();core.on("messages",batch=>{manager?.window?.webContents.send("chat:messages",batch);for(const m of batch||[]){if(m.eventType&&m.eventType!=="chat")streamOverlay.pushEvent(m);else{streamOverlay.pushChat(m);hologram.push(m)}}});core.on("status",s=>manager?.window?.webContents.send("chat:status",s))});
app.on("window-all-closed",()=>{if(process.platform!=="darwin")app.quit()});app.on("before-quit",()=>{void streamOverlay?.stop?.();void hologram?.stop?.()});
