"use strict";
const {contextBridge,ipcRenderer}=require("electron");
const invoke=(name,...args)=>ipcRenderer.invoke(name,...args);
contextBridge.exposeInMainWorld("batto",{
  chatHistory:o=>invoke("chat:history",o||{}),chatClear:p=>invoke("chat:clear",p||"all"),chatStatuses:()=>invoke("chat:statuses"),chatConnect:(p,c)=>invoke("chat:connect",p,c||{}),chatDisconnect:p=>invoke("chat:disconnect",p),onChatMessages:cb=>ipcRenderer.on("chat:messages",(_e,data)=>cb(data)),onChatStatus:cb=>ipcRenderer.on("chat:status",(_e,data)=>cb(data)),toggleAlwaysOnTop:()=>invoke("window:alwaysOnTop"),
  settingsGet:()=>invoke("settings:get"),settingsPatch:v=>invoke("settings:patch",v||{}),
  obsStatus:()=>invoke("obs:status"),obsConnect:c=>invoke("obs:connect",c||{}),obsDisconnect:()=>invoke("obs:disconnect"),obsSavedPassword:()=>invoke("obs:savedPassword"),obsScenes:()=>invoke("obs:scenes"),obsSceneItems:s=>invoke("obs:sceneItems",s),obsSetScene:s=>invoke("obs:setScene",s),obsSetItemEnabled:v=>invoke("obs:setItemEnabled",v),obsEnsureOverlay:v=>invoke("obs:ensureOverlay",v||{}),obsEnsureHologram:v=>invoke("obs:ensureHologram",v||{}),
  overlayStatus:()=>invoke("overlay:status"),overlayOpen:()=>invoke("overlay:open"),overlayOpenEditor:()=>invoke("overlay:openEditor"),overlayCopyUrl:()=>invoke("overlay:copyUrl"),overlayTestChat:()=>invoke("overlay:testChat"),overlayTestEvent:()=>invoke("overlay:testEvent"),overlayTestGift:n=>invoke("overlay:testGift",n),hologramStatus:()=>invoke("hologram:status"),hologramOpen:()=>invoke("hologram:open"),hologramCopyUrl:()=>invoke("hologram:copyUrl"),
  tiktokApiKeyStatus:()=>invoke("tiktok:apiKeyStatus"),tiktokSetApiKey:k=>invoke("tiktok:setApiKey",k),tiktokClearApiKey:()=>invoke("tiktok:clearApiKey"),
  tiktokOAuthStatus:()=>invoke("tiktok:oauthStatus"),tiktokOAuthBegin:c=>invoke("tiktok:oauthBegin",c||{}),tiktokOAuthRefresh:()=>invoke("tiktok:oauthRefresh"),tiktokOAuthRevoke:()=>invoke("tiktok:oauthRevoke"),tiktokResolveContext:u=>invoke("tiktok:resolveContext",u),tiktokContext:()=>invoke("tiktok:context"),
  tiktokGifts:o=>invoke("tiktok:gifts",o||{}),tiktokGift:id=>invoke("tiktok:gift",id),tiktokGiftSearch:q=>invoke("tiktok:giftSearch",q),tiktokGiftTest:n=>invoke("tiktok:giftTest",n),tiktokGiftTestPresets:()=>invoke("tiktok:giftTestPresets"),tiktokGiftGallery:()=>invoke("tiktok:giftGallery"),tiktokEarnings:p=>invoke("tiktok:earnings",p),
  tiktokSendChat:m=>invoke("tiktok:sendChat",m),tiktokMuted:()=>invoke("tiktok:muted"),tiktokMute:v=>invoke("tiktok:mute",v),tiktokUnmute:u=>invoke("tiktok:unmute",u),tiktokBanned:()=>invoke("tiktok:banned"),tiktokBan:v=>invoke("tiktok:ban",v),tiktokUnban:u=>invoke("tiktok:unban",u),tiktokModerators:()=>invoke("tiktok:moderators"),tiktokAddModerator:u=>invoke("tiktok:addModerator",u),tiktokRemoveModerator:u=>invoke("tiktok:removeModerator",u),tiktokComments:e=>invoke("tiktok:comments",e),tiktokSensitiveWords:()=>invoke("tiktok:sensitiveWords"),tiktokAddSensitiveWord:w=>invoke("tiktok:addSensitiveWord",w),tiktokDeleteSensitiveWord:id=>invoke("tiktok:deleteSensitiveWord",id),
  tiktokLiveCenterOpen:()=>invoke("tiktok:liveCenterOpen"),tiktokLiveCenterSummary:()=>invoke("tiktok:liveCenterSummary"),tiktokLiveCenterRoomDetails:id=>invoke("tiktok:liveCenterRoomDetails",id),tiktokLiveCenterInteractions:v=>invoke("tiktok:liveCenterInteractions",v),
  twitchOAuthStatus:()=>invoke("twitch:oauthStatus"),twitchOAuthBegin:c=>invoke("twitch:oauthBegin",c||{}),twitchOAuthRefresh:()=>invoke("twitch:oauthRefresh"),twitchOAuthRevoke:()=>invoke("twitch:oauthRevoke"),twitchConnect:c=>invoke("twitch:connect",c),
  youtubeOAuthStatus:()=>invoke("youtube:oauthStatus"),youtubeOAuthBegin:c=>invoke("youtube:oauthBegin",c||{}),youtubeOAuthRefresh:()=>invoke("youtube:oauthRefresh"),youtubeOAuthRevoke:()=>invoke("youtube:oauthRevoke"),youtubeConnect:c=>invoke("youtube:connect",c||{}),cngConnect:c=>invoke("cng:connect",c||{})
});
