"use strict";
const {contextBridge,ipcRenderer}=require("electron");
contextBridge.exposeInMainWorld("batto",{
  chatHistory:o=>ipcRenderer.invoke("chat:history",o||{}),chatClear:p=>ipcRenderer.invoke("chat:clear",p||"all"),chatStatuses:()=>ipcRenderer.invoke("chat:statuses"),chatConnect:(p,c)=>ipcRenderer.invoke("chat:connect",p,c||{}),chatDisconnect:p=>ipcRenderer.invoke("chat:disconnect",p),onChatMessages:cb=>ipcRenderer.on("chat:messages",(_e,data)=>cb(data)),onChatStatus:cb=>ipcRenderer.on("chat:status",(_e,data)=>cb(data)),toggleAlwaysOnTop:()=>ipcRenderer.invoke("window:alwaysOnTop"),
  settingsGet:()=>ipcRenderer.invoke("settings:get"),settingsPatch:v=>ipcRenderer.invoke("settings:patch",v||{}),
  obsStatus:()=>ipcRenderer.invoke("obs:status"),obsConnect:c=>ipcRenderer.invoke("obs:connect",c||{}),obsDisconnect:()=>ipcRenderer.invoke("obs:disconnect"),obsSavedPassword:()=>ipcRenderer.invoke("obs:savedPassword"),obsScenes:()=>ipcRenderer.invoke("obs:scenes"),obsSceneItems:s=>ipcRenderer.invoke("obs:sceneItems",s),obsSetScene:s=>ipcRenderer.invoke("obs:setScene",s),obsSetItemEnabled:v=>ipcRenderer.invoke("obs:setItemEnabled",v),obsEnsureOverlay:v=>ipcRenderer.invoke("obs:ensureOverlay",v||{}),
  overlayStatus:()=>ipcRenderer.invoke("overlay:status"),overlayOpen:()=>ipcRenderer.invoke("overlay:open"),overlayOpenEditor:()=>ipcRenderer.invoke("overlay:openEditor"),overlayCopyUrl:()=>ipcRenderer.invoke("overlay:copyUrl"),overlayTestChat:()=>ipcRenderer.invoke("overlay:testChat"),overlayTestEvent:()=>ipcRenderer.invoke("overlay:testEvent"),
  tiktokOAuthStatus:()=>ipcRenderer.invoke("tiktok:oauthStatus"),tiktokOAuthBegin:c=>ipcRenderer.invoke("tiktok:oauthBegin",c||{}),tiktokOAuthRefresh:()=>ipcRenderer.invoke("tiktok:oauthRefresh"),tiktokOAuthRevoke:()=>ipcRenderer.invoke("tiktok:oauthRevoke"),tiktokResolveContext:u=>ipcRenderer.invoke("tiktok:resolveContext",u),tiktokContext:()=>ipcRenderer.invoke("tiktok:context"),tiktokGifts:()=>ipcRenderer.invoke("tiktok:gifts"),tiktokGiftSearch:q=>ipcRenderer.invoke("tiktok:giftSearch",q),tiktokSendChat:m=>ipcRenderer.invoke("tiktok:sendChat",m),tiktokMuted:()=>ipcRenderer.invoke("tiktok:muted"),tiktokMute:v=>ipcRenderer.invoke("tiktok:mute",v),tiktokUnmute:u=>ipcRenderer.invoke("tiktok:unmute",u),tiktokBanned:()=>ipcRenderer.invoke("tiktok:banned"),tiktokBan:v=>ipcRenderer.invoke("tiktok:ban",v),tiktokUnban:u=>ipcRenderer.invoke("tiktok:unban",u),tiktokModerators:()=>ipcRenderer.invoke("tiktok:moderators"),tiktokAddModerator:u=>ipcRenderer.invoke("tiktok:addModerator",u),tiktokRemoveModerator:u=>ipcRenderer.invoke("tiktok:removeModerator",u),tiktokComments:e=>ipcRenderer.invoke("tiktok:comments",e),tiktokSensitiveWords:()=>ipcRenderer.invoke("tiktok:sensitiveWords"),tiktokAddSensitiveWord:w=>ipcRenderer.invoke("tiktok:addSensitiveWord",w),tiktokDeleteSensitiveWord:w=>ipcRenderer.invoke("tiktok:deleteSensitiveWord",w),
  twitchOAuthStatus:()=>ipcRenderer.invoke("twitch:oauthStatus"),twitchOAuthBegin:c=>ipcRenderer.invoke("twitch:oauthBegin",c||{}),twitchOAuthRefresh:()=>ipcRenderer.invoke("twitch:oauthRefresh"),twitchOAuthRevoke:()=>ipcRenderer.invoke("twitch:oauthRevoke"),twitchConnect:c=>ipcRenderer.invoke("twitch:connect",c),
  youtubeOAuthStatus:()=>ipcRenderer.invoke("youtube:oauthStatus"),youtubeOAuthBegin:c=>ipcRenderer.invoke("youtube:oauthBegin",c||{}),youtubeOAuthRefresh:()=>ipcRenderer.invoke("youtube:oauthRefresh"),youtubeOAuthRevoke:()=>ipcRenderer.invoke("youtube:oauthRevoke"),youtubeConnect:c=>ipcRenderer.invoke("youtube:connect",c||{}),
  cngConnect:c=>ipcRenderer.invoke("cng:connect",c||{})
});
