"use strict";
const crypto=require("node:crypto");
const http=require("node:http");
const b64url=b=>Buffer.from(b).toString("base64url");
const DEFAULT_SCOPES=["https://www.googleapis.com/auth/youtube.force-ssl"];
class YouTubeOAuth{
  constructor({secretStore,settingsStore,shell,port=48733}={}){this.secretStore=secretStore;this.settingsStore=settingsStore;this.shell=shell;this.port=port;this.pendingServer=null;}
  async begin({clientId,clientSecret,scopes=DEFAULT_SCOPES}={}){
    const cfg=await this.settingsStore.get("youtubeOAuth")||{};clientId=String(clientId||cfg.clientId||"").trim();if(!clientId)throw new Error("Google/YouTube Client ID fehlt. Erstelle einen OAuth-Client vom Typ Desktop-App.");
    if(clientSecret)await this.secretStore.set("youtube.clientSecret",clientSecret);
    const state=crypto.randomBytes(24).toString("hex"),verifier=b64url(crypto.randomBytes(48)),challenge=b64url(crypto.createHash("sha256").update(verifier).digest()),redirectUri=`http://127.0.0.1:${this.port}`;
    await this.settingsStore.set("youtubeOAuth",{clientId,redirectUri,scopes});
    const url=new URL("https://accounts.google.com/o/oauth2/v2/auth");url.searchParams.set("client_id",clientId);url.searchParams.set("redirect_uri",redirectUri);url.searchParams.set("response_type","code");url.searchParams.set("scope",scopes.join(" "));url.searchParams.set("state",state);url.searchParams.set("code_challenge",challenge);url.searchParams.set("code_challenge_method","S256");url.searchParams.set("access_type","offline");url.searchParams.set("prompt","consent");
    const pending=this.waitCallback(state,verifier,redirectUri);await this.shell.openExternal(url.toString());return pending;
  }
  waitCallback(state,verifier,redirectUri){if(this.pendingServer)try{this.pendingServer.close()}catch{}return new Promise((resolve,reject)=>{const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,"http://127.0.0.1");if(u.searchParams.get("state")!==state)throw new Error("Ungültiger Google OAuth-State.");if(u.searchParams.get("error"))throw new Error(u.searchParams.get("error_description")||u.searchParams.get("error"));const code=u.searchParams.get("code");if(!code)throw new Error("Google hat keinen Authorization Code geliefert.");const result=await this.exchange(code,verifier,redirectUri);res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end("<h2>BATTO MULTI-CHAT</h2><p>YouTube wurde erfolgreich verbunden. Du kannst dieses Fenster schließen.</p>");server.close();this.pendingServer=null;resolve(result);}catch(e){res.writeHead(400,{"Content-Type":"text/plain; charset=utf-8"});res.end(String(e.message||e));server.close();this.pendingServer=null;reject(e);}});server.on("error",e=>{this.pendingServer=null;reject(e)});server.listen(this.port,"127.0.0.1");this.pendingServer=server;});}
  async exchange(code,verifier,redirectUri){const cfg=await this.settingsStore.get("youtubeOAuth")||{};const secret=await this.secretStore.get("youtube.clientSecret");const body=new URLSearchParams({client_id:cfg.clientId,code,code_verifier:verifier,grant_type:"authorization_code",redirect_uri:redirectUri});if(secret)body.set("client_secret",secret);const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error_description||data.error||`Google OAuth HTTP ${response.status}`);await this.save(data);return this.status();}
  async refresh(){const cfg=await this.settingsStore.get("youtubeOAuth")||{},refresh=await this.secretStore.get("youtube.refreshToken"),secret=await this.secretStore.get("youtube.clientSecret");if(!refresh)throw new Error("Kein YouTube Refresh Token vorhanden. Bitte neu anmelden.");const body=new URLSearchParams({client_id:cfg.clientId,refresh_token:refresh,grant_type:"refresh_token"});if(secret)body.set("client_secret",secret);const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error_description||data.error||`Google OAuth HTTP ${response.status}`);await this.save(data);return this.status();}
  async save(data){if(data.access_token)await this.secretStore.set("youtube.accessToken",data.access_token);if(data.refresh_token)await this.secretStore.set("youtube.refreshToken",data.refresh_token);const old=await this.settingsStore.get("youtubeSession")||{};await this.settingsStore.set("youtubeSession",{expiresAt:Date.now()+Number(data.expires_in||3600)*1000,scope:String(data.scope||old.scope?.join(" ")||"").split(" ").filter(Boolean),updatedAt:Date.now()});}
  async accessToken(){const s=await this.settingsStore.get("youtubeSession")||{};if(s.expiresAt&&Date.now()>s.expiresAt-120000)await this.refresh();return this.secretStore.get("youtube.accessToken");}
  async status(){const t=await this.secretStore.get("youtube.accessToken"),s=await this.settingsStore.get("youtubeSession")||{},cfg=await this.settingsStore.get("youtubeOAuth")||{};return{connected:Boolean(t),configured:Boolean(cfg.clientId),scopes:s.scope||[],expiresAt:s.expiresAt||0};}
  async revoke(){const token=await this.secretStore.get("youtube.accessToken");if(token)await fetch(`https://oauth2.googleapis.com/revoke?token=${encodeURIComponent(token)}`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"}}).catch(()=>{});for(const k of ["youtube.accessToken","youtube.refreshToken"])await this.secretStore.delete(k);await this.settingsStore.set("youtubeSession",{});return this.status();}
}
module.exports={YouTubeOAuth,DEFAULT_SCOPES};
