"use strict";
(()=>{
const api=window.batto,root=document.getElementById("multi-chat-root");
const meta={all:["Alle","#5aa7ff","✦"],twitch:["Twitch","#9146ff","◉"],cng:["CNG","#2f9cff","◆"],tiktok:["TikTok","#ddd","♪"],youtube:["YouTube","#ff3030","▶"]};
let filter="all",messages=[],settingsPage="accounts",settings={},oauth={connected:false,scopes:[]},context={};
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const $=s=>root.querySelector(s);
function page(k,n){return`<button data-settings-page="${k}" class="${settingsPage===k?'active':''}">${n}</button>`}
function accountCard(title,key,desc,body){return`<div class="card"><div class="card-head"><strong>${title}</strong><span class="status-dot" id="status-${key}"></span></div><p class="muted">${desc}</p>${body}</div>`}
function settingsHtml(){return`<section class="settings-shell" id="settings" hidden><header class="settings-top"><div><strong>Einstellungen & Datenschutz</strong><div class="muted">BATTO MULTI-CHAT</div></div><button class="icon-btn" id="settings-close">✕</button></header><div class="settings-body"><nav class="settings-nav">${page("accounts","Konten")}${page("moderation","Moderation")}${page("filters","Chatfilter")}${page("tts","TTS")}${page("gifts","Geschenke")}${page("guests","Multi-Gast")}${page("obs","OBS & Overlay")}${page("privacy","Datenschutz")}${page("diagnostics","Diagnose")}</nav><main class="settings-content">${settingsPages()}</main></div></section>`}
function settingsPages(){const tt=settings.accounts?.tiktok?.username||"";const oauthCfg=settings.tiktokOAuth||{};return`
<section class="settings-page ${settingsPage==='accounts'?'active':''}"><h2>Konten & Verbindungen</h2><p>Anmeldungen wie in einer normalen Desktop-App. Tokens werden nicht im Chatfenster angezeigt.</p>
${accountCard("TikTok","tiktok",oauth.connected?"TikTok/Euler OAuth verbunden.":"Sichere TikTok-Anmeldung über Euler OAuth mit TikTok-QR-Code.",`<label>TikTok @Username<input id="tt-user" value="${esc(tt)}" placeholder="@Crazy_Batto"></label><div class="row"><button class="primary" id="tt-oauth">${oauth.connected?"TikTok erneut autorisieren":"Mit TikTok anmelden"}</button>${oauth.connected?'<button id="tt-revoke">Konto trennen</button>':''}<button id="tt-live">LIVE-Reader verbinden</button></div><div id="tt-oauth-state" class="muted"></div><details><summary>Einmalige App-Einrichtung</summary><label>Euler OAuth Client ID<input id="tt-client-id" value="${esc(oauthCfg.clientId||"")}" placeholder="Client ID"></label><label>Euler OAuth Client Secret<input id="tt-client-secret" type="password" placeholder="wird verschlüsselt gespeichert"></label><p class="muted">Client Secret bleibt ausschließlich im Electron-Main-Prozess und wird über Windows safeStorage gespeichert.</p></details>`) }
${accountCard("Twitch","twitch","Eigener Connector mit OAuth-Anmeldung.",'<div class="row"><button disabled>Mit Twitch anmelden</button></div>')}
${accountCard("YouTube","youtube","Eigener Connector mit Google/YouTube OAuth.",'<div class="row"><button disabled>Mit YouTube anmelden</button></div>')}
${accountCard("CNG","cng","Eigener CNG-Connector.",'<div class="row"><button disabled>CNG einrichten</button></div>')}</section>
<section class="settings-page ${settingsPage==='moderation'?'active':''}"><h2>Moderation</h2><p>TikTok-Schnellmoderation und zentrale Listen.</p><div class="card"><div class="row"><button id="resolve-context">LIVE-Kontext laden</button><button id="load-mutes">Stummgeschaltete</button><button id="load-bans">Gesperrte</button><button id="load-mods">Moderatoren</button></div><div id="moderation-context" class="muted"></div><div id="moderation-list" class="diag">Noch keine Liste geladen.</div></div><div class="card"><label><input id="comments-enabled" type="checkbox" checked> Kommentare aktiv</label><button id="save-comments">Übernehmen</button></div></section>
<section class="settings-page ${settingsPage==='filters'?'active':''}"><h2>Chatfilter</h2><p>TikTok Sensitive-Words und lokale Filter.</p><div class="card"><div class="row"><button id="load-words">Von TikTok laden</button></div><label>Wort hinzufügen<input id="word-input" placeholder="Begriff"></label><div class="row"><button id="add-word">Hinzufügen</button></div><div id="word-list" class="diag">Noch nicht geladen.</div></div></section>
<section class="settings-page ${settingsPage==='tts'?'active':''}"><h2>TTS</h2><p>Stimme, Sprache, Lautstärke, Geschwindigkeit und Plattformfilter werden als eigenes Modul angebunden.</p><div class="card muted">Keine Windows-Hardware- oder Sensorfunktionen in diesem Projekt.</div></section>
<section class="settings-page ${settingsPage==='gifts'?'active':''}"><h2>Geschenke</h2><p>Euler Gift-Katalog für TikTok LIVE.</p><div class="card"><div class="row"><button id="load-gifts">Gift-Katalog laden</button><input id="gift-search" placeholder="Geschenk suchen"><button id="search-gifts">Suchen</button></div><div id="gift-list" class="diag">Noch keine Gifts geladen.</div></div></section>
<section class="settings-page ${settingsPage==='guests'?'active':''}"><h2>Multi-Gast</h2><p>Gast-Slots werden sauber an OBS-Quellen gekoppelt. Plattformfunktionen nur, wenn die jeweilige API sie wirklich unterstützt.</p><div class="card muted">Multi-Gast-Modul vorbereitet – ohne Hardware- oder Sensorabhängigkeiten.</div></section>
<section class="settings-page ${settingsPage==='obs'?'active':''}"><h2>OBS & Overlay</h2><p>OBS WebSocket und lokale Browserquelle.</p><div class="card"><label>OBS WebSocket URL<input id="obs-url" value="${esc(settings.obs?.url||"ws://127.0.0.1:4455")}"></label><label>Passwort<input id="obs-pass" type="password" placeholder="gespeichertes Passwort wird automatisch verwendet"></label><div class="row"><button id="obs-connect">OBS verbinden</button><button id="obs-disconnect">Trennen</button></div><div id="obs-state" class="muted"></div></div><div class="card"><div class="perm"><span>OBS-Browserquelle</span><strong id="overlay-url">http://127.0.0.1:48621/overlay</strong></div><div class="row"><button id="overlay-open">Öffnen</button><button id="overlay-copy">URL kopieren</button><button id="overlay-chat">Chat testen</button><button id="overlay-event">Geschenk testen</button></div><div id="overlay-state" class="muted"></div></div></section>
<section class="settings-page ${settingsPage==='privacy'?'active':''}"><h2>Datenschutz & Sicherheit</h2><p>Normale Einstellungen und Secrets sind getrennt.</p><div class="card"><div class="perm"><span>Renderer-Zugriff auf Secrets</span><span class="ok">gesperrt</span></div><div class="perm"><span>Electron Context Isolation</span><span class="ok">aktiv</span></div><div class="perm"><span>OAuth/OBS-Secrets</span><span class="ok">safeStorage</span></div></div></section>
<section class="settings-page ${settingsPage==='diagnostics'?'active':''}"><h2>Diagnose</h2><p>Technische Details nur hier.</p><div class="diag" id="diag">Lade Status …</div></section>`}
function render(){root.innerHTML=`<div class="multi-chat"><header class="chat-head"><div class="chat-title"><span style="font-size:18px">✦</span><div><strong>BATTO MULTI-CHAT</strong><small>Twitch · CNG · TikTok · YouTube</small></div></div><div class="chat-actions"><button class="icon-btn" id="open-settings">⚙</button><button class="icon-btn" id="always-top">⌃</button></div></header><nav class="chat-tabs">${Object.entries(meta).map(([k,v])=>`<button class="chat-tab ${filter===k?'active':''}" data-filter="${k}" ${k!=="all"?`data-platform="${k}"`:""}>${v[0]}</button>`).join("")}</nav><section class="chat-body" id="chat-body"></section><section class="chat-compose"><textarea id="chat-input" maxlength="1000" placeholder="Nachricht schreiben …"></textarea><div class="compose-row"><small>Nachrichtenversand nur über authentifizierte Plattformen.</small><button class="send-btn" id="chat-send">Senden</button></div></section><footer class="chat-footer"><span id="chat-status">● Initialisiere …</span><span id="chat-count">0 Nachrichten</span></footer>${settingsHtml()}<div class="context-menu" id="context-menu" hidden></div></div>`;bind();updateBody();refreshStatuses();}
function bind(){root.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$("#open-settings").onclick=()=>{$("#settings").hidden=false;refreshStatuses()};$("#settings-close").onclick=()=>$("#settings").hidden=true;$("#always-top").onclick=()=>api.toggleAlwaysOnTop();root.querySelectorAll("[data-settings-page]").forEach(b=>b.onclick=()=>{settingsPage=b.dataset.settingsPage;render();$("#settings").hidden=false});
$("#tt-oauth")?.addEventListener("click",async()=>{try{const username=$("#tt-user").value.trim();const clientId=$("#tt-client-id").value.trim();const clientSecret=$("#tt-client-secret").value.trim();const accounts=settings.accounts||{};accounts.tiktok={...(accounts.tiktok||{}),username};settings.accounts=accounts;settings.tiktokOAuth={...(settings.tiktokOAuth||{}),clientId};await api.settingsPatch({accounts,tiktokOAuth:settings.tiktokOAuth});$("#tt-oauth-state").textContent="TikTok-Anmeldung geöffnet – QR-Code in TikTok bestätigen …";oauth=await api.tiktokOAuthBegin({clientId,clientSecret});$("#tt-oauth-state").textContent="✓ TikTok verbunden";await refreshStatuses();}catch(e){$("#tt-oauth-state").textContent=`Fehler: ${e.message}`}});
$("#tt-revoke")?.addEventListener("click",async()=>{oauth=await api.tiktokOAuthRevoke();render();$("#settings").hidden=false});$("#tt-live")?.addEventListener("click",async()=>{try{await api.chatConnect("tiktok",{username:$("#tt-user").value});await api.tiktokResolveContext($("#tt-user").value);await refreshStatuses();}catch(e){alert(e.message)}});
$("#resolve-context")?.addEventListener("click",async()=>{try{context=await api.tiktokResolveContext(settings.accounts?.tiktok?.username||"");showContext();}catch(e){$("#moderation-context").textContent=e.message}});
$("#load-mutes")?.addEventListener("click",()=>loadList(api.tiktokMuted,"Stummgeschaltete Nutzer"));$("#load-bans")?.addEventListener("click",()=>loadList(api.tiktokBanned,"Gesperrte Nutzer"));$("#load-mods")?.addEventListener("click",()=>loadList(api.tiktokModerators,"Moderatoren"));$("#save-comments")?.addEventListener("click",async()=>{try{await api.tiktokComments($("#comments-enabled").checked);alert("Kommentarstatus aktualisiert.")}catch(e){alert(e.message)}});
$("#load-words")?.addEventListener("click",async()=>{try{$("#word-list").textContent=JSON.stringify(await api.tiktokSensitiveWords(),null,2)}catch(e){$("#word-list").textContent=e.message}});$("#add-word")?.addEventListener("click",async()=>{try{await api.tiktokAddSensitiveWord($("#word-input").value);$("#word-list").textContent=JSON.stringify(await api.tiktokSensitiveWords(),null,2)}catch(e){$("#word-list").textContent=e.message}});
$("#load-gifts")?.addEventListener("click",async()=>{try{$("#gift-list").textContent=JSON.stringify(await api.tiktokGifts(),null,2)}catch(e){$("#gift-list").textContent=e.message}});$("#search-gifts")?.addEventListener("click",async()=>{try{$("#gift-list").textContent=JSON.stringify(await api.tiktokGiftSearch($("#gift-search").value),null,2)}catch(e){$("#gift-list").textContent=e.message}});
$("#obs-connect")?.addEventListener("click",async()=>{try{setObsState(await api.obsConnect({url:$("#obs-url").value,password:$("#obs-pass").value}))}catch(e){setObsState({connected:false,error:e.message})}});$("#obs-disconnect")?.addEventListener("click",async()=>setObsState(await api.obsDisconnect()));$("#overlay-open")?.addEventListener("click",()=>api.overlayOpen());$("#overlay-copy")?.addEventListener("click",()=>api.overlayCopyUrl());$("#overlay-chat")?.addEventListener("click",()=>api.overlayTestChat());$("#overlay-event")?.addEventListener("click",()=>api.overlayTestEvent());
$("#chat-send").onclick=sendMessage;document.addEventListener("click",()=>{const m=$("#context-menu");if(m)m.hidden=true},{once:true});}
async function sendMessage(){const input=$("#chat-input"),text=input.value.trim();if(!text)return;if(filter!=="tiktok"){alert("Direktes Senden ist aktuell nur für authentifiziertes TikTok vorbereitet.");return;}try{await api.tiktokSendChat(text);input.value="";}catch(e){alert(e.message)}}
function updateBody(){const body=$("#chat-body"),visible=messages.filter(m=>filter==="all"||m.platform===filter).slice(-300);$("#chat-count").textContent=`${visible.length} Nachrichten`;if(!visible.length){body.innerHTML='<div class="chat-empty"><div><strong>Noch keine Nachrichten</strong><br><small>Verbinde Twitch/CNG/TikTok oder YouTube, um alles in einem Verlauf zu sehen.</small></div></div>';return;}body.innerHTML=visible.map((m,i)=>{const v=meta[m.platform]||meta.all;return`<div class="chat-row" data-message-index="${messages.indexOf(m)}"><span class="platform-badge" style="background:${esc(v[1])}">${v[2]}</span><div><div class="chat-meta"><span class="chat-user" style="color:${esc(v[1])}">${esc(m.displayName||m.username)}</span><span class="chat-role">${esc(v[0])}</span>${m.role?`<span class="chat-role">${esc(m.role)}</span>`:""}</div><div class="chat-message">${esc(m.message)}</div></div></div>`}).join("");body.querySelectorAll(".chat-row").forEach(row=>row.oncontextmenu=e=>openContext(e,messages[Number(row.dataset.messageIndex)]));body.scrollTop=body.scrollHeight;}
function openContext(e,m){e.preventDefault();if(!m||m.platform!=="tiktok")return;const menu=$("#context-menu");menu.innerHTML=`<strong>${esc(m.username||m.displayName||"TikTok User")}</strong><button data-action="mute">Stummschalten</button><button data-action="unmute">Stummschaltung aufheben</button><button data-action="ban">Sperren</button><button data-action="unban">Entsperren</button><button data-action="mod">Zum Moderator machen</button><button data-action="unmod">Moderator entfernen</button><button data-action="copyname">Benutzername kopieren</button>`;menu.style.left=`${Math.min(e.clientX,window.innerWidth-230)}px`;menu.style.top=`${Math.min(e.clientY,window.innerHeight-280)}px`;menu.hidden=false;menu.querySelectorAll("button").forEach(b=>b.onclick=async ev=>{ev.stopPropagation();try{const id=m.userId||m.metadata?.userId||m.metadata?.user?.userId||"";if(["mute","unmute","ban","unban","mod","unmod"].includes(b.dataset.action)&&!id)throw new Error("Für diese Nachricht ist keine TikTok User-ID vorhanden.");if(b.dataset.action==="mute")await api.tiktokMute({userId:id,duration:300,commentMsgId:m.metadata?.msgId});if(b.dataset.action==="unmute")await api.tiktokUnmute(id);if(b.dataset.action==="ban")await api.tiktokBan({userId:id,commentMsgId:m.metadata?.msgId});if(b.dataset.action==="unban")await api.tiktokUnban(id);if(b.dataset.action==="mod")await api.tiktokAddModerator(id);if(b.dataset.action==="unmod")await api.tiktokRemoveModerator(id);if(b.dataset.action==="copyname")navigator.clipboard.writeText(m.username||m.displayName||"");menu.hidden=true;}catch(err){alert(err.message)}});}
async function loadList(fn,title){try{$("#moderation-list").textContent=`${title}\n\n${JSON.stringify(await fn(),null,2)}`}catch(e){$("#moderation-list").textContent=e.message}}
function showContext(){if($("#moderation-context"))$("#moderation-context").textContent=`@${context.username||"-"} · Room ${context.roomId||"-"} · Anchor ${context.anchorId||"-"}`}
async function refreshStatuses(){if(!api)return;settings=await api.settingsGet();oauth=await api.tiktokOAuthStatus();context=await api.tiktokContext();const s=await api.chatStatuses();for(const [k,v] of Object.entries(s)){const dot=$(`#status-${k}`);if(dot)dot.classList.toggle("on",Boolean(v.connected));}const ttDot=$("#status-tiktok");if(ttDot&&oauth.connected)ttDot.classList.add("on");setObsState(await api.obsStatus());const ov=await api.overlayStatus();if($("#overlay-url"))$("#overlay-url").textContent=ov.overlayUrl||"http://127.0.0.1:48621/overlay";if($("#overlay-state"))$("#overlay-state").textContent=ov.active?`● Lokal aktiv · Port ${ov.port}`:"○ Overlay offline";showContext();if($("#tt-oauth-state"))$("#tt-oauth-state").textContent=oauth.connected?`✓ Angemeldet · ${oauth.scopes?.length||0} Berechtigungen`:"○ Nicht angemeldet";const diag=$("#diag");if(diag)diag.textContent=JSON.stringify({platforms:s,tiktokOAuth:oauth,tiktokContext:context,obs:await api.obsStatus(),overlay:ov},null,2);}
function setObsState(s){const el=$("#obs-state");if(el)el.textContent=s?.connected?`● Verbunden · ${s.url}`:`○ Nicht verbunden${s?.error?` · ${s.error}`:""}`}
async function init(){settings=await api.settingsGet();oauth=await api.tiktokOAuthStatus();render();messages=await api.chatHistory({limit:300});updateBody();api.onChatMessages(batch=>{messages.push(...batch);if(messages.length>1000)messages=messages.slice(-1000);updateBody()});api.onChatStatus(()=>{const el=$("#chat-status");if(el)el.textContent="● Verbindungen aktualisiert";refreshStatuses()});}
init();
})();
