"use strict";
(()=>{
const api=window.batto,root=document.getElementById("multi-chat-root");
const platformMeta={all:["Alle","#5aa7ff","✦"],twitch:["Twitch","#9146ff","◉"],cng:["CNG","#2f9cff","◆"],tiktok:["TikTok","#eeeeee","♪"],youtube:["YouTube","#ff3030","▶"]};
let filter="all",messages=[],settingsPage="accounts",settings={},status={},ttAuth={},twAuth={},ytAuth={},ttContext={},selectedObsScene="",ttsQueue=[],ttsBusy=false;
const $=s=>root.querySelector(s),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const fmtTime=t=>t?new Date(Number(t)).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"}):"";
function nav(k,n){return`<button data-page="${k}" class="${settingsPage===k?'active':''}">${n}</button>`}
function card(title,key,description,content){return`<article class="card"><div class="card-head"><strong>${title}</strong><span id="status-${key}" class="status-dot"></span></div><p class="muted">${description}</p>${content}</article>`}
function accountSummary(auth,profile={}){if(!auth?.connected)return`<span class="muted">○ Nicht angemeldet</span>`;return`<span class="ok">● Angemeldet</span>${profile?.displayName||profile?.username?`<span class="muted"> · ${esc(profile.displayName||profile.username)}</span>`:""}`}
function settingsShell(){return`<section class="settings-shell" id="settings" hidden><header class="settings-top"><div><strong>Einstellungen & Datenschutz</strong><div class="muted">BATTO MULTI-CHAT</div></div><button id="settings-close" class="icon-btn">✕</button></header><div class="settings-body"><nav class="settings-nav">${nav("accounts","Konten")}${nav("moderation","Moderation")}${nav("filters","Chatfilter")}${nav("tts","TTS")}${nav("gifts","Geschenke")}${nav("guests","Multi-Gast")}${nav("obs","OBS & Overlay")}${nav("privacy","Datenschutz")}${nav("diagnostics","Diagnose")}</nav><main class="settings-content">${settingsPages()}</main></div></section>`}
function settingsPages(){const a=settings.accounts||{},tt=settings.tiktokOAuth||{},tw=settings.twitchOAuth||{},yt=settings.youtubeOAuth||{},cng=a.cng||{},tts=settings.tts||{enabled:false,language:"de-DE",rate:1,pitch:1,volume:1,platforms:["twitch","cng","tiktok","youtube"]};return`
<section class="settings-page ${settingsPage==='accounts'?'active':''}"><h2>Konten & Verbindungen</h2><p>Plattformkonten werden getrennt angemeldet. Geheimnisse bleiben im Main-Prozess.</p>
${card("TikTok","tiktok","Euler OAuth 2.0 mit TikTok-QR-Code und separatem LIVE-Reader.",`${accountSummary(ttAuth,a.tiktok)}<label>TikTok @Username<input id="tt-user" value="${esc(a.tiktok?.username||"")}" placeholder="@Crazy_Batto"></label><div class="row"><button class="primary" id="tt-login">${ttAuth.connected?"TikTok neu autorisieren":"Mit TikTok anmelden"}</button><button id="tt-live">LIVE-Reader verbinden</button>${ttAuth.connected?'<button id="tt-logout">Konto trennen</button>':''}</div><div id="tt-login-state" class="muted"></div><details><summary>Einmalige App-Einrichtung</summary><label>Euler OAuth Client ID<input id="tt-client-id" value="${esc(tt.clientId||"")}"></label><label>Euler OAuth Client Secret<input id="tt-client-secret" type="password" placeholder="verschlüsselt speichern"></label></details>`) }
${card("Twitch","twitch","Twitch OAuth im Systembrowser; Chat läuft danach über den Twitch-Connector.",`${accountSummary(twAuth,twAuth.profile||a.twitch)}<label>Kanal<input id="tw-channel" value="${esc(a.twitch?.channel||a.twitch?.username||"")}" placeholder="crazy_batto"></label><div class="row"><button class="primary" id="tw-login">${twAuth.connected?"Twitch neu autorisieren":"Mit Twitch anmelden"}</button>${twAuth.connected?'<button id="tw-connect">Chat verbinden</button><button id="tw-logout">Konto trennen</button>':''}</div><div id="tw-login-state" class="muted"></div><details><summary>Einmalige App-Einrichtung</summary><label>Twitch Client ID<input id="tw-client-id" value="${esc(tw.clientId||"")}"></label><label>Twitch Client Secret<input id="tw-client-secret" type="password" placeholder="verschlüsselt speichern"></label></details>`) }
${card("YouTube","youtube","Google/YouTube Desktop-OAuth mit PKCE und Loopback-Callback.",`${accountSummary(ytAuth,a.youtube)}<label>Live-Video-ID<input id="yt-video" value="${esc(a.youtube?.videoId||"")}" placeholder="YouTube Live Video ID"></label><div class="row"><button class="primary" id="yt-login">${ytAuth.connected?"YouTube neu autorisieren":"Mit YouTube anmelden"}</button>${ytAuth.connected?'<button id="yt-connect">Live-Chat verbinden</button><button id="yt-logout">Konto trennen</button>':''}</div><div id="yt-login-state" class="muted"></div><details><summary>Einmalige App-Einrichtung</summary><label>Google OAuth Client ID<input id="yt-client-id" value="${esc(yt.clientId||"")}"></label><label>Client Secret (falls vorhanden)<input id="yt-client-secret" type="password" placeholder="optional / verschlüsselt"></label></details>`) }
${card("CNG","cng","Eigener isolierter Connector. Kein unbestätigtes Plattformprotokoll wird erfunden.",`<label>Realtime WebSocket URL<input id="cng-url" value="${esc(cng.websocketUrl||"")}" placeholder="wss://..."></label><label>Token<input id="cng-token" type="password" placeholder="optional / verschlüsselt"></label><div class="row"><button id="cng-connect">CNG verbinden</button><button data-disconnect="cng">Trennen</button></div>`) }
</section>
<section class="settings-page ${settingsPage==='moderation'?'active':''}"><h2>Moderation</h2><p>TikTok-Moderation zentral und zusätzlich per Rechtsklick im Chat.</p><div class="card"><div class="row"><button id="tt-context">LIVE-Kontext laden</button><button id="load-mutes">Stummgeschaltete</button><button id="load-bans">Gesperrte</button><button id="load-mods">Moderatoren</button></div><div id="context-state" class="muted"></div><div id="moderation-list" class="diag">Noch keine Liste geladen.</div></div><div class="card"><label><input id="comments-enabled" type="checkbox" checked> TikTok-Kommentare aktiv</label><button id="save-comments">Übernehmen</button></div></section>
<section class="settings-page ${settingsPage==='filters'?'active':''}"><h2>Chatfilter</h2><p>TikTok Sensitive-Words und lokale Filterregeln.</p><div class="card"><div class="row"><button id="load-words">TikTok-Wörter laden</button></div><label>Wort hinzufügen<input id="word-input" placeholder="Begriff"></label><div class="row"><button id="add-word">Hinzufügen</button></div><div id="word-list" class="diag">Noch nicht geladen.</div></div></section>
<section class="settings-page ${settingsPage==='tts'?'active':''}"><h2>TTS</h2><p>Lokale Sprachausgabe für Chatnachrichten.</p><div class="card"><label><input id="tts-enabled" type="checkbox" ${tts.enabled?'checked':''}> TTS aktiv</label><label>Sprache<select id="tts-language"><option ${tts.language==='de-DE'?'selected':''}>de-DE</option><option ${tts.language==='en-US'?'selected':''}>en-US</option><option ${tts.language==='es-ES'?'selected':''}>es-ES</option></select></label><label>Geschwindigkeit<input id="tts-rate" type="range" min="0.5" max="2" step="0.05" value="${Number(tts.rate||1)}"></label><label>Tonhöhe<input id="tts-pitch" type="range" min="0" max="2" step="0.05" value="${Number(tts.pitch||1)}"></label><label>Lautstärke<input id="tts-volume" type="range" min="0" max="1" step="0.05" value="${Number(tts.volume??1)}"></label><div class="row"><button id="tts-save">Speichern</button><button id="tts-test">Testen</button></div></div></section>
<section class="settings-page ${settingsPage==='gifts'?'active':''}"><h2>Geschenke</h2><p>TikTok Gift-Katalog über Euler Stream.</p><div class="card"><div class="row"><button id="load-gifts">Katalog laden</button><input id="gift-search" placeholder="Geschenk suchen"><button id="search-gifts">Suchen</button></div><div id="gift-list" class="diag">Noch keine Gifts geladen.</div></div></section>
<section class="settings-page ${settingsPage==='guests'?'active':''}"><h2>Multi-Gast</h2><p>OBS-Quellen als Gast-Slots verwalten.</p><div class="card"><div class="row"><select id="guest-scene"></select><button id="guest-load">Quellen laden</button></div><div id="guest-list" class="diag">OBS verbinden und Szene auswählen.</div></div></section>
<section class="settings-page ${settingsPage==='obs'?'active':''}"><h2>OBS & Overlay</h2><p>OBS WebSocket sowie lokale Browserquelle auf Port 48621.</p><div class="card"><label>OBS WebSocket URL<input id="obs-url" value="${esc(settings.obs?.url||"ws://127.0.0.1:4455")}"></label><label>Passwort<input id="obs-pass" type="password" placeholder="gespeichertes Passwort automatisch verwenden"></label><div class="row"><button id="obs-connect">OBS verbinden</button><button id="obs-disconnect">Trennen</button><button id="obs-scenes">Szenen laden</button></div><div id="obs-state" class="muted"></div><label>Szene<select id="obs-scene"></select></label><div class="row"><button id="obs-set-scene">Szene aktivieren</button><button id="obs-add-overlay">BATTO Overlay als Browserquelle anlegen</button></div></div><div class="card"><div class="perm"><span>OBS-Browserquelle</span><strong id="overlay-url">http://127.0.0.1:48621/overlay</strong></div><div class="row"><button id="overlay-editor">Overlay bearbeiten</button><button id="overlay-open">Overlay öffnen</button><button id="overlay-copy">URL kopieren</button><button id="overlay-chat">Chat testen</button><button id="overlay-event">Geschenk testen</button></div><div id="overlay-state" class="muted"></div></div></section>
<section class="settings-page ${settingsPage==='privacy'?'active':''}"><h2>Datenschutz & Sicherheit</h2><p>Secrets werden verschlüsselt und nicht im Renderer gespeichert.</p><div class="card"><div class="perm"><span>Context Isolation</span><span class="ok">aktiv</span></div><div class="perm"><span>OAuth-/OBS-Secrets</span><span class="ok">Electron safeStorage</span></div><div class="perm"><span>Hardware-/Sensorzugriff</span><span class="ok">nicht vorhanden</span></div><div class="perm"><span>Plugin-System</span><span class="ok">nicht vorhanden</span></div></div></section>
<section class="settings-page ${settingsPage==='diagnostics'?'active':''}"><h2>Diagnose</h2><p>Technische Zustände bleiben aus dem Live-Chat heraus.</p><div class="diag" id="diag">Lade Status …</div></section>`}
function render(){root.innerHTML=`<div class="multi-chat"><header class="chat-head"><div class="chat-title"><span style="font-size:18px">✦</span><div><strong>BATTO MULTI-CHAT</strong><small>Twitch · CNG · TikTok · YouTube</small></div></div><div class="chat-actions"><button id="open-settings" class="icon-btn" title="Einstellungen">⚙</button><button id="always-top" class="icon-btn" title="Immer im Vordergrund">⌃</button></div></header><nav class="chat-tabs">${Object.entries(platformMeta).map(([k,v])=>`<button class="chat-tab ${filter===k?'active':''}" data-filter="${k}" ${k!=="all"?`data-platform="${k}"`:""}>${v[0]}</button>`).join("")}</nav><section id="chat-body" class="chat-body"></section><section class="chat-compose"><textarea id="chat-input" maxlength="1000" placeholder="Nachricht schreiben …"></textarea><div class="compose-row"><small>Versand nur über unterstützte, angemeldete Plattformen.</small><button id="chat-send" class="send-btn">Senden</button></div></section><footer class="chat-footer"><span id="chat-status">● Initialisiere …</span><span id="chat-count">0 Nachrichten</span></footer>${settingsShell()}<div id="context-menu" class="context-menu" hidden></div></div>`;bind();updateBody();void refresh();}
function openSettings(page=settingsPage){settingsPage=page;render();$("#settings").hidden=false;}
function bind(){root.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render()});$("#open-settings").onclick=()=>{$("#settings").hidden=false;void refresh()};$("#settings-close").onclick=()=>$("#settings").hidden=true;$("#always-top").onclick=()=>api.toggleAlwaysOnTop();root.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>openSettings(b.dataset.page));root.querySelectorAll("[data-disconnect]").forEach(b=>b.onclick=async()=>{await api.chatDisconnect(b.dataset.disconnect);await refresh()});
$("#tt-login")?.addEventListener("click",async()=>loginTikTok());$("#tt-logout")?.addEventListener("click",async()=>{ttAuth=await api.tiktokOAuthRevoke();openSettings("accounts")});$("#tt-live")?.addEventListener("click",async()=>{try{const u=$("#tt-user").value.trim();await saveAccount("tiktok",{username:u});await api.chatConnect("tiktok",{username:u});ttContext=await api.tiktokResolveContext(u);await refresh()}catch(e){show("#tt-login-state",e.message,true)}});
$("#tw-login")?.addEventListener("click",loginTwitch);$("#tw-logout")?.addEventListener("click",async()=>{twAuth=await api.twitchOAuthRevoke();openSettings("accounts")});$("#tw-connect")?.addEventListener("click",async()=>{try{const channel=$("#tw-channel").value.trim();await saveAccount("twitch",{...(settings.accounts?.twitch||{}),channel});await api.twitchConnect(channel);await refresh()}catch(e){show("#tw-login-state",e.message,true)}});
$("#yt-login")?.addEventListener("click",loginYouTube);$("#yt-logout")?.addEventListener("click",async()=>{ytAuth=await api.youtubeOAuthRevoke();openSettings("accounts")});$("#yt-connect")?.addEventListener("click",async()=>{try{const videoId=$("#yt-video").value.trim();await saveAccount("youtube",{...(settings.accounts?.youtube||{}),videoId});await api.youtubeConnect({videoId});await refresh()}catch(e){show("#yt-login-state",e.message,true)}});
$("#cng-connect")?.addEventListener("click",async()=>{try{const websocketUrl=$("#cng-url").value.trim(),token=$("#cng-token").value.trim();await api.cngConnect({websocketUrl,token});await refresh()}catch(e){alert(e.message)}});
$("#tt-context")?.addEventListener("click",async()=>{try{ttContext=await api.tiktokResolveContext(settings.accounts?.tiktok?.username||"");showContext()}catch(e){show("#context-state",e.message,true)}});$("#load-mutes")?.addEventListener("click",()=>loadJson("#moderation-list","Stummgeschaltete Nutzer",api.tiktokMuted));$("#load-bans")?.addEventListener("click",()=>loadJson("#moderation-list","Gesperrte Nutzer",api.tiktokBanned));$("#load-mods")?.addEventListener("click",()=>loadJson("#moderation-list","Moderatoren",api.tiktokModerators));$("#save-comments")?.addEventListener("click",async()=>{try{await api.tiktokComments($("#comments-enabled").checked);alert("Kommentarstatus aktualisiert.")}catch(e){alert(e.message)}});
$("#load-words")?.addEventListener("click",()=>loadJson("#word-list","Sensitive Words",api.tiktokSensitiveWords));$("#add-word")?.addEventListener("click",async()=>{try{await api.tiktokAddSensitiveWord($("#word-input").value.trim());await loadJson("#word-list","Sensitive Words",api.tiktokSensitiveWords)}catch(e){show("#word-list",e.message,true)}});
$("#load-gifts")?.addEventListener("click",()=>loadJson("#gift-list","Gift-Katalog",api.tiktokGifts));$("#search-gifts")?.addEventListener("click",()=>loadJson("#gift-list","Gift-Suche",()=>api.tiktokGiftSearch($("#gift-search").value.trim())));
$("#tts-save")?.addEventListener("click",saveTts);$("#tts-test")?.addEventListener("click",()=>speakText("BATTO MULTI-CHAT TTS Test"));
$("#obs-connect")?.addEventListener("click",async()=>{try{setObs(await api.obsConnect({url:$("#obs-url").value,password:$("#obs-pass").value}));await loadScenes()}catch(e){setObs({connected:false,error:e.message})}});$("#obs-disconnect")?.addEventListener("click",async()=>setObs(await api.obsDisconnect()));$("#obs-scenes")?.addEventListener("click",loadScenes);$("#obs-set-scene")?.addEventListener("click",async()=>{const s=$("#obs-scene").value;if(s){await api.obsSetScene(s);selectedObsScene=s}});$("#obs-add-overlay")?.addEventListener("click",async()=>{try{const scene=$("#obs-scene").value;if(!scene)throw new Error("Bitte zuerst eine OBS-Szene auswählen.");await api.obsEnsureOverlay({sceneName:scene,inputName:"BATTO Stream Overlay",width:2560,height:1440});alert("BATTO Stream Overlay wurde der OBS-Szene hinzugefügt bzw. war bereits vorhanden.")}catch(e){alert(e.message)}});
$("#overlay-editor")?.addEventListener("click",()=>api.overlayOpenEditor());$("#overlay-open")?.addEventListener("click",()=>api.overlayOpen());$("#overlay-copy")?.addEventListener("click",()=>api.overlayCopyUrl());$("#overlay-chat")?.addEventListener("click",()=>api.overlayTestChat());$("#overlay-event")?.addEventListener("click",()=>api.overlayTestEvent());
$("#guest-load")?.addEventListener("click",()=>loadGuestItems($("#guest-scene").value));$("#chat-send").onclick=sendMessage;}
async function loginTikTok(){try{const username=$("#tt-user").value.trim(),clientId=$("#tt-client-id").value.trim(),clientSecret=$("#tt-client-secret").value.trim();await saveAccount("tiktok",{username});settings.tiktokOAuth={...(settings.tiktokOAuth||{}),clientId};await api.settingsPatch({tiktokOAuth:settings.tiktokOAuth});show("#tt-login-state","TikTok-QR-Anmeldung wurde geöffnet …");ttAuth=await api.tiktokOAuthBegin({clientId,clientSecret});show("#tt-login-state","✓ TikTok verbunden");await refresh()}catch(e){show("#tt-login-state",e.message,true)}}
async function loginTwitch(){try{const clientId=$("#tw-client-id").value.trim(),clientSecret=$("#tw-client-secret").value.trim();settings.twitchOAuth={...(settings.twitchOAuth||{}),clientId};await api.settingsPatch({twitchOAuth:settings.twitchOAuth});show("#tw-login-state","Twitch-Anmeldung wurde im Browser geöffnet …");twAuth=await api.twitchOAuthBegin({clientId,clientSecret});show("#tw-login-state","✓ Twitch verbunden");await refresh()}catch(e){show("#tw-login-state",e.message,true)}}
async function loginYouTube(){try{const clientId=$("#yt-client-id").value.trim(),clientSecret=$("#yt-client-secret").value.trim();settings.youtubeOAuth={...(settings.youtubeOAuth||{}),clientId};await api.settingsPatch({youtubeOAuth:settings.youtubeOAuth});show("#yt-login-state","Google/YouTube-Anmeldung wurde geöffnet …");ytAuth=await api.youtubeOAuthBegin({clientId,clientSecret});show("#yt-login-state","✓ YouTube verbunden");await refresh()}catch(e){show("#yt-login-state",e.message,true)}}
async function saveAccount(platform,value){const accounts={...(settings.accounts||{}),[platform]:value};settings.accounts=accounts;await api.settingsPatch({accounts})}
async function sendMessage(){const input=$("#chat-input"),text=input.value.trim();if(!text)return;try{if(filter==="tiktok")await api.tiktokSendChat(text);else throw new Error("Senden ist für diese Plattform noch nicht freigeschaltet.");input.value=""}catch(e){alert(e.message)}}
function updateBody(){const body=$("#chat-body"),visible=messages.filter(m=>filter==="all"||m.platform===filter).slice(-300);$("#chat-count").textContent=`${visible.length} Nachrichten`;if(!visible.length){body.innerHTML='<div class="chat-empty"><div><strong>Noch keine Nachrichten</strong><br><small>Verbinde Twitch/CNG/TikTok oder YouTube, um alles in einem Verlauf zu sehen.</small></div></div>';return}body.innerHTML=visible.map(m=>{const v=platformMeta[m.platform]||platformMeta.all;return`<div class="chat-row" data-index="${messages.indexOf(m)}"><span class="platform-badge" style="background:${esc(v[1])}">${v[2]}</span><div><div class="chat-meta"><span class="chat-user" style="color:${esc(v[1])}">${esc(m.displayName||m.username||"User")}</span><span class="chat-role">${esc(v[0])}</span>${m.role?`<span class="chat-role">${esc(m.role)}</span>`:""}<small>${fmtTime(m.timestamp)}</small></div><div class="chat-message">${esc(m.message)}</div></div></div>`}).join("");body.querySelectorAll(".chat-row").forEach(r=>r.oncontextmenu=e=>openContext(e,messages[Number(r.dataset.index)]));body.scrollTop=body.scrollHeight}
function openContext(e,m){e.preventDefault();if(m?.platform!=="tiktok")return;const menu=$("#context-menu"),id=m.userId||m.metadata?.userId||m.metadata?.user?.userId||"";menu.innerHTML=`<strong>${esc(m.username||m.displayName||"TikTok User")}</strong><button data-a="mute">Stummschalten</button><button data-a="unmute">Stummschaltung aufheben</button><button data-a="ban">Sperren</button><button data-a="unban">Entsperren</button><button data-a="mod">Zum Moderator machen</button><button data-a="unmod">Moderator entfernen</button><button data-a="copy">Benutzername kopieren</button>`;menu.style.left=`${Math.min(e.clientX,window.innerWidth-235)}px`;menu.style.top=`${Math.min(e.clientY,window.innerHeight-290)}px`;menu.hidden=false;menu.querySelectorAll("button").forEach(b=>b.onclick=async ev=>{ev.stopPropagation();try{if(b.dataset.a!=="copy"&&!id)throw new Error("Keine TikTok User-ID in dieser Nachricht.");if(b.dataset.a==="mute")await api.tiktokMute({userId:id,duration:300,commentMsgId:m.metadata?.msgId});if(b.dataset.a==="unmute")await api.tiktokUnmute(id);if(b.dataset.a==="ban")await api.tiktokBan({userId:id,commentMsgId:m.metadata?.msgId});if(b.dataset.a==="unban")await api.tiktokUnban(id);if(b.dataset.a==="mod")await api.tiktokAddModerator(id);if(b.dataset.a==="unmod")await api.tiktokRemoveModerator(id);if(b.dataset.a==="copy")await navigator.clipboard.writeText(m.username||m.displayName||"");menu.hidden=true}catch(err){alert(err.message)}});setTimeout(()=>document.addEventListener("click",()=>menu.hidden=true,{once:true}),0)}
async function refresh(){settings=await api.settingsGet();[status,ttAuth,twAuth,ytAuth,ttContext]=await Promise.all([api.chatStatuses(),api.tiktokOAuthStatus(),api.twitchOAuthStatus(),api.youtubeOAuthStatus(),api.tiktokContext()]);for(const [k,v] of Object.entries(status)){const dot=$(`#status-${k}`);if(dot)dot.classList.toggle("on",Boolean(v.connected))}if(ttAuth.connected)$("#status-tiktok")?.classList.add("on");if(twAuth.connected)$("#status-twitch")?.classList.add("on");if(ytAuth.connected)$("#status-youtube")?.classList.add("on");setObs(await api.obsStatus());const ov=await api.overlayStatus();if($("#overlay-url"))$("#overlay-url").textContent=ov.overlayUrl||"http://127.0.0.1:48621/overlay";show("#overlay-state",ov.active?`● Lokal aktiv · ${ov.overlayUrl}`:"○ Overlay offline");showContext();await populateGuestScenes();const diag=$("#diag");if(diag)diag.textContent=JSON.stringify({platforms:status,tiktokOAuth:ttAuth,twitchOAuth:twAuth,youtubeOAuth:ytAuth,tiktokContext:ttContext,obs:await api.obsStatus(),overlay:ov},null,2)}
function setObs(s){show("#obs-state",s?.connected?`● Verbunden · ${s.url}`:`○ Nicht verbunden${s?.lastError||s?.error?` · ${s.lastError||s.error}`:""}`,!s?.connected&&Boolean(s?.lastError||s?.error))}
async function loadScenes(){try{const data=await api.obsScenes();selectedObsScene=data.current||selectedObsScene;for(const sel of [$("#obs-scene"),$("#guest-scene")])if(sel){sel.innerHTML=(data.scenes||[]).map(x=>`<option ${x.name===selectedObsScene?'selected':''}>${esc(x.name)}</option>`).join("")}return data}catch(e){show("#obs-state",e.message,true)}}
async function populateGuestScenes(){if(!$("#guest-scene")&&!$("#obs-scene"))return;const obsStatus=await api.obsStatus();if(obsStatus.connected)await loadScenes()}
async function loadGuestItems(scene){try{if(!scene)throw new Error("Szene auswählen.");const items=await api.obsSceneItems(scene),eligible=items.filter(i=>/browser|camera|video|ndi|capture|ffmpeg|decklink/i.test(`${i.inputKind||""} ${i.sourceName||""}`));const box=$("#guest-list");box.innerHTML=eligible.length?eligible.map(i=>`<div class="perm"><span>${esc(i.sourceName)}</span><label><input type="checkbox" data-guest-id="${i.sceneItemId}" ${i.enabled?'checked':''}> sichtbar</label></div>`).join(""):"Keine geeigneten Gast-/Videoquellen gefunden.";box.querySelectorAll("[data-guest-id]").forEach(x=>x.onchange=()=>api.obsSetItemEnabled({sceneName:scene,sceneItemId:Number(x.dataset.guestId),enabled:x.checked}))}catch(e){show("#guest-list",e.message,true)}}
async function loadJson(selector,title,fn){try{const data=await fn();show(selector,`${title}\n\n${JSON.stringify(data,null,2)}`)}catch(e){show(selector,e.message,true)}}
function showContext(){show("#context-state",ttContext?.username?`@${ttContext.username} · Room ${ttContext.roomId||"-"} · Anchor ${ttContext.anchorId||"-"}`:"Noch kein TikTok LIVE-Kontext geladen.")}
function show(selector,text,error=false){const el=$(selector);if(el){el.textContent=text||"";el.style.color=error?"var(--bad)":""}}
async function saveTts(){settings.tts={enabled:$("#tts-enabled").checked,language:$("#tts-language").value,rate:Number($("#tts-rate").value),pitch:Number($("#tts-pitch").value),volume:Number($("#tts-volume").value),platforms:["twitch","cng","tiktok","youtube"]};await api.settingsPatch({tts:settings.tts})}
function speakText(text){if(!window.speechSynthesis)return;const t=settings.tts||{language:"de-DE",rate:1,pitch:1,volume:1};const u=new SpeechSynthesisUtterance(String(text));u.lang=t.language||"de-DE";u.rate=Number(t.rate||1);u.pitch=Number(t.pitch||1);u.volume=Number(t.volume??1);window.speechSynthesis.speak(u)}
function queueTts(m){const t=settings.tts||{};if(!t.enabled||!m?.message||(t.platforms?.length&&!t.platforms.includes(m.platform)))return;ttsQueue.push(`${m.displayName||m.username||"User"} sagt: ${m.message}`);pumpTts()}
function pumpTts(){if(ttsBusy||!ttsQueue.length||!window.speechSynthesis)return;ttsBusy=true;const t=settings.tts||{},u=new SpeechSynthesisUtterance(ttsQueue.shift());u.lang=t.language||"de-DE";u.rate=Number(t.rate||1);u.pitch=Number(t.pitch||1);u.volume=Number(t.volume??1);u.onend=u.onerror=()=>{ttsBusy=false;pumpTts()};window.speechSynthesis.speak(u)}
async function init(){settings=await api.settingsGet();render();messages=await api.chatHistory({limit:300});updateBody();api.onChatMessages(batch=>{for(const m of batch){messages.push(m);queueTts(m)}if(messages.length>1000)messages=messages.slice(-1000);updateBody()});api.onChatStatus(()=>{show("#chat-status","● Verbindungen aktualisiert");void refresh()})}
init().catch(e=>{root.innerHTML=`<pre style="padding:20px;color:#ff8080">${esc(e.stack||e.message||e)}</pre>`});
})();
